name: Create and publish a Docker image

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.repos.outputs.value }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Matrix
        id: repos
        shell: bash
        run: |
          array=""
          for f in *; do
            if [ -d "$f" ];then
              if [[ ! -n "$array" ]]; then
                array='"'$f'"'
              else
                array=$array", "'"'$f'"'
              fi
            fi
          done
          echo "::set-output name=value::[$array]"
  docker:
    runs-on: ubuntu-latest
    needs: [ setup ]
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        dir: ${{fromJson(needs.setup.outputs.repos)}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.dir }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.dir }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
